version: '3'
services:

    web:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: bash -c "sleep 10 && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
        restart: always
        ports:
            - 80:8000
        depends_on:
            - db
        environment:
            HOST: db

    db:
        image: postgis/postgis:11-2.5
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres